export const cfg = () => ({
  port: parseInt(process.env.PORT ?? '3000', 10),
  databaseUrl: process.env.DATABASE_URL!,
  resendApiKey: process.env.RESEND_API_KEY!,
  resendFrom: process.env.RESEND_FROM ?? 'NestTest <no-reply@nesttest.com>',
  resendBcc: process.env.RESEND_BCC ?? '',
  slackBotToken: process.env.SLACK_BOT_TOKEN!,
  slackChannelId: process.env.SLACK_CHANNEL_ID!,
  easypostApiKey: process.env.EASYPOST_API_KEY!,
  fromAddress: {
    name: process.env.SHIP_FROM_NAME ?? 'NestTest Fulfillment',
    street1: process.env.SHIP_FROM_STREET1 ?? '123 Warehouse Ave',
    city: process.env.SHIP_FROM_CITY ?? 'Miami',
    state: process.env.SHIP_FROM_STATE ?? 'FL',
    zip: process.env.SHIP_FROM_ZIP ?? '33101',
    phone: process.env.SHIP_FROM_PHONE ?? '3051234567',
  },
  labAddress: {
    name: process.env.LAB_NAME ?? 'NestTest Lab',
    street1: process.env.LAB_STREET1 ?? '1 Lab Way',
    city: process.env.LAB_CITY ?? 'Atlanta',
    state: process.env.LAB_STATE ?? 'GA',
    zip: process.env.LAB_ZIP ?? '30301',
    phone: process.env.LAB_PHONE ?? '4041234567',
  },
  defaultWeightOz: parseInt(process.env.DEFAULT_WEIGHT_OZ ?? '8', 10),
  defaultService: process.env.DEFAULT_SERVICE ?? 'USPS_GROUND_ADVANTAGE',
  pickup: {
    instructions: process.env.PICKUP_INSTRUCTIONS ?? 'Front desk',
    minTime: process.env.PICKUP_MIN_TIME ?? '15:00',
    maxTime: process.env.PICKUP_MAX_TIME ?? '18:00',
  },
  webhookSecret: process.env.WEBHOOK_SECRET ?? 'dev-secret',
  appBaseUrl: process.env.APP_BASE_URL ?? 'http://localhost:3000',
});
